2025-02-23 23:43:23,091 - logger - INFO - CUSUM plot created successfully.
2025-02-23 23:59:23,597 - logger - ERROR - Error in Bayesian change point analysis: Compilation failed (return status=1):
"C:\MinGW\bin\g++.EXE" -shared -g -Wno-c++11-narrowing -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"c:\Users\Tsegaye\anaconda3\Lib\site-packages\numpy\core\include" -I"c:\Users\Tsegaye\anaconda3\include" -I"c:\Users\Tsegaye\anaconda3\Lib\site-packages\pytensor\link\c\c_code" -L"c:\Users\Tsegaye\anaconda3\libs" -L"c:\Users\Tsegaye\anaconda3" -o "C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\lazylinker_ext.pyd" "C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\mod.cpp" "c:\Users\Tsegaye\anaconda3\python312.dll"
C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\mod.cpp:1:0: sorry, unimplemented: 64-bit mode not compiled in
 #include "pytensor_mod_helper.h"
 

2025-02-24 00:01:24,686 - logger - ERROR - Error in Bayesian change point analysis: Compilation failed (return status=1):
"C:\MinGW\bin\g++.EXE" -shared -g -Wno-c++11-narrowing -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"c:\Users\Tsegaye\anaconda3\Lib\site-packages\numpy\core\include" -I"c:\Users\Tsegaye\anaconda3\include" -I"c:\Users\Tsegaye\anaconda3\Lib\site-packages\pytensor\link\c\c_code" -L"c:\Users\Tsegaye\anaconda3\libs" -L"c:\Users\Tsegaye\anaconda3" -o "C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\lazylinker_ext.pyd" "C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\mod.cpp" "c:\Users\Tsegaye\anaconda3\python312.dll"
C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\mod.cpp:1:0: sorry, unimplemented: 64-bit mode not compiled in
 #include "pytensor_mod_helper.h"
 

2025-02-24 01:19:58,432 - logger - ERROR - Error in Bayesian change point analysis: Compilation failed (return status=1):
"C:\MinGW\bin\g++.EXE" -shared -g -Wno-c++11-narrowing -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"c:\Users\Tsegaye\anaconda3\Lib\site-packages\numpy\core\include" -I"c:\Users\Tsegaye\anaconda3\include" -I"c:\Users\Tsegaye\anaconda3\Lib\site-packages\pytensor\link\c\c_code" -L"c:\Users\Tsegaye\anaconda3\libs" -L"c:\Users\Tsegaye\anaconda3" -o "C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\lazylinker_ext.pyd" "C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\mod.cpp" "c:\Users\Tsegaye\anaconda3\python312.dll"
'"C:\MinGW\bin\g++.EXE"' is not recognized as an internal or external command,
operable program or batch file.

2025-02-24 08:24:17,221 - logger - INFO - CUSUM plot created successfully.
2025-02-24 08:27:57,173 - logger - ERROR - Error in Bayesian change point analysis: Compilation failed (return status=1):
"C:\msys64\ucrt64\bin\g++.EXE" -shared -g -Wno-c++11-narrowing -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -march=skylake -mmmx -mpopcnt -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mavx2 -mno-sse4a -mno-fma4 -mno-xop -mfma -mno-avx512f -mbmi -mbmi2 -maes -mpclmul -mno-avx512vl -mno-avx512bw -mno-avx512dq -mno-avx512cd -mno-avx512vbmi -mno-avx512ifma -mno-avx512vpopcntdq -mno-avx512vbmi2 -mno-gfni -mno-vpclmulqdq -mno-avx512vnni -mno-avx512bitalg -mno-avx512bf16 -mno-avx512vp2intersect -mno-3dnow -madx -mabm -mno-cldemote -mclflushopt -mno-clwb -mno-clzero -mcx16 -mno-enqcmd -mf16c -mfsgsbase -mfxsr -mhle -msahf -mno-lwp -mlzcnt -mmovbe -mno-movdir64b -mno-movdiri -mno-mwaitx -mno-pconfig -mno-pku -mprfchw -mno-ptwrite -mno-rdpid -mrdrnd -mrdseed -mrtm -mno-serialize -mno-sgx -mno-sha -mno-shstk -mno-tbm -mno-tsxldtrk -mno-vaes -mno-waitpkg -mno-wbnoinvd -mxsave -mxsavec -mxsaveopt -mxsaves -mno-amx-tile -mno-amx-int8 -mno-amx-bf16 -mno-uintr -mno-hreset -mno-kl -mno-widekl -mno-avxvnni -mno-avx512fp16 -mno-avxifma -mno-avxvnniint8 -mno-avxneconvert -mno-cmpccxadd -mno-amx-fp16 -mno-prefetchi -mno-raoint -mno-amx-complex -mno-avxvnniint16 -mno-sm3 -mno-sha512 -mno-sm4 -mno-apxf -mno-usermsr --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=8192 -mtune=skylake -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"c:\Users\Tsegaye\anaconda3\Lib\site-packages\numpy\core\include" -I"c:\Users\Tsegaye\anaconda3\include" -I"c:\Users\Tsegaye\anaconda3\Lib\site-packages\pytensor\link\c\c_code" -L"c:\Users\Tsegaye\anaconda3\libs" -L"c:\Users\Tsegaye\anaconda3" -o "C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\lazylinker_ext.pyd" "C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\mod.cpp" "c:\Users\Tsegaye\anaconda3\python312.dll"
In file included from c:\Users\Tsegaye\anaconda3\include/Python.h:12,
                 from c:\Users\Tsegaye\anaconda3\Lib\site-packages\pytensor\link\c\c_code/pytensor_mod_helper.h:4,
                 from C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\mod.cpp:1:
c:\Users\Tsegaye\anaconda3\include/pyconfig.h:240:9: warning: "MS_WIN64" redefined
  240 | #define MS_WIN64
      |         ^~~~~~~~
<command-line>: note: this is the location of the previous definition
cc1plus.exe: note: unrecognized command-line option '-Wno-c++11-narrowing' may have been intended to silence earlier diagnostics
collect2.exe: error: ld returned 116 exit status

2025-02-24 08:35:42,393 - logger - INFO - CUSUM plot created successfully.
2025-02-24 08:39:25,288 - logger - ERROR - Error in Bayesian change point analysis: Compilation failed (return status=1):
"C:\msys64\ucrt64\bin\g++.EXE" -shared -g -Wno-c++11-narrowing -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -march=skylake -mmmx -mpopcnt -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mavx2 -mno-sse4a -mno-fma4 -mno-xop -mfma -mno-avx512f -mbmi -mbmi2 -maes -mpclmul -mno-avx512vl -mno-avx512bw -mno-avx512dq -mno-avx512cd -mno-avx512vbmi -mno-avx512ifma -mno-avx512vpopcntdq -mno-avx512vbmi2 -mno-gfni -mno-vpclmulqdq -mno-avx512vnni -mno-avx512bitalg -mno-avx512bf16 -mno-avx512vp2intersect -mno-3dnow -madx -mabm -mno-cldemote -mclflushopt -mno-clwb -mno-clzero -mcx16 -mno-enqcmd -mf16c -mfsgsbase -mfxsr -mhle -msahf -mno-lwp -mlzcnt -mmovbe -mno-movdir64b -mno-movdiri -mno-mwaitx -mno-pconfig -mno-pku -mprfchw -mno-ptwrite -mno-rdpid -mrdrnd -mrdseed -mrtm -mno-serialize -mno-sgx -mno-sha -mno-shstk -mno-tbm -mno-tsxldtrk -mno-vaes -mno-waitpkg -mno-wbnoinvd -mxsave -mxsavec -mxsaveopt -mxsaves -mno-amx-tile -mno-amx-int8 -mno-amx-bf16 -mno-uintr -mno-hreset -mno-kl -mno-widekl -mno-avxvnni -mno-avx512fp16 -mno-avxifma -mno-avxvnniint8 -mno-avxneconvert -mno-cmpccxadd -mno-amx-fp16 -mno-prefetchi -mno-raoint -mno-amx-complex -mno-avxvnniint16 -mno-sm3 -mno-sha512 -mno-sm4 -mno-apxf -mno-usermsr --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=8192 -mtune=skylake -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"c:\Users\Tsegaye\anaconda3\Lib\site-packages\numpy\core\include" -I"c:\Users\Tsegaye\anaconda3\include" -I"c:\Users\Tsegaye\anaconda3\Lib\site-packages\pytensor\link\c\c_code" -L"c:\Users\Tsegaye\anaconda3\libs" -L"c:\Users\Tsegaye\anaconda3" -o "C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\lazylinker_ext.pyd" "C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\mod.cpp" "c:\Users\Tsegaye\anaconda3\python312.dll"
In file included from c:\Users\Tsegaye\anaconda3\include/Python.h:12,
                 from c:\Users\Tsegaye\anaconda3\Lib\site-packages\pytensor\link\c\c_code/pytensor_mod_helper.h:4,
                 from C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\mod.cpp:1:
c:\Users\Tsegaye\anaconda3\include/pyconfig.h:240:9: warning: "MS_WIN64" redefined
  240 | #define MS_WIN64
      |         ^~~~~~~~
<command-line>: note: this is the location of the previous definition
cc1plus.exe: note: unrecognized command-line option '-Wno-c++11-narrowing' may have been intended to silence earlier diagnostics
collect2.exe: error: ld returned 116 exit status

2025-02-24 09:17:36,265 - logger - INFO - CUSUM plot created successfully.
2025-02-24 09:20:52,665 - logger - ERROR - Error in Bayesian change point analysis: Compilation failed (return status=1):
"C:\msys64\ucrt64\bin\g++.EXE" -shared -g -Wno-c++11-narrowing -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -march=skylake -mmmx -mpopcnt -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mavx2 -mno-sse4a -mno-fma4 -mno-xop -mfma -mno-avx512f -mbmi -mbmi2 -maes -mpclmul -mno-avx512vl -mno-avx512bw -mno-avx512dq -mno-avx512cd -mno-avx512vbmi -mno-avx512ifma -mno-avx512vpopcntdq -mno-avx512vbmi2 -mno-gfni -mno-vpclmulqdq -mno-avx512vnni -mno-avx512bitalg -mno-avx512bf16 -mno-avx512vp2intersect -mno-3dnow -madx -mabm -mno-cldemote -mclflushopt -mno-clwb -mno-clzero -mcx16 -mno-enqcmd -mf16c -mfsgsbase -mfxsr -mhle -msahf -mno-lwp -mlzcnt -mmovbe -mno-movdir64b -mno-movdiri -mno-mwaitx -mno-pconfig -mno-pku -mprfchw -mno-ptwrite -mno-rdpid -mrdrnd -mrdseed -mrtm -mno-serialize -mno-sgx -mno-sha -mno-shstk -mno-tbm -mno-tsxldtrk -mno-vaes -mno-waitpkg -mno-wbnoinvd -mxsave -mxsavec -mxsaveopt -mxsaves -mno-amx-tile -mno-amx-int8 -mno-amx-bf16 -mno-uintr -mno-hreset -mno-kl -mno-widekl -mno-avxvnni -mno-avx512fp16 -mno-avxifma -mno-avxvnniint8 -mno-avxneconvert -mno-cmpccxadd -mno-amx-fp16 -mno-prefetchi -mno-raoint -mno-amx-complex -mno-avxvnniint16 -mno-sm3 -mno-sha512 -mno-sm4 -mno-apxf -mno-usermsr --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=8192 -mtune=skylake -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"c:\Users\Tsegaye\anaconda3\Lib\site-packages\numpy\core\include" -I"c:\Users\Tsegaye\anaconda3\include" -I"c:\Users\Tsegaye\anaconda3\Lib\site-packages\pytensor\link\c\c_code" -L"c:\Users\Tsegaye\anaconda3\libs" -L"c:\Users\Tsegaye\anaconda3" -o "C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\lazylinker_ext.pyd" "C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\mod.cpp" "c:\Users\Tsegaye\anaconda3\python312.dll"
In file included from c:\Users\Tsegaye\anaconda3\include/Python.h:12,
                 from c:\Users\Tsegaye\anaconda3\Lib\site-packages\pytensor\link\c\c_code/pytensor_mod_helper.h:4,
                 from C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\mod.cpp:1:
c:\Users\Tsegaye\anaconda3\include/pyconfig.h:240:9: warning: "MS_WIN64" redefined
  240 | #define MS_WIN64
      |         ^~~~~~~~
<command-line>: note: this is the location of the previous definition
cc1plus.exe: note: unrecognized command-line option '-Wno-c++11-narrowing' may have been intended to silence earlier diagnostics
collect2.exe: error: ld returned 116 exit status

2025-02-24 09:28:16,128 - logger - INFO - CUSUM plot created successfully.
2025-02-24 09:31:51,374 - logger - ERROR - Error in Bayesian change point analysis: Compilation failed (return status=1):
"C:\msys64\ucrt64\bin\g++.EXE" -shared -g -Wno-c++11-narrowing -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -march=skylake -mmmx -mpopcnt -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mavx2 -mno-sse4a -mno-fma4 -mno-xop -mfma -mno-avx512f -mbmi -mbmi2 -maes -mpclmul -mno-avx512vl -mno-avx512bw -mno-avx512dq -mno-avx512cd -mno-avx512vbmi -mno-avx512ifma -mno-avx512vpopcntdq -mno-avx512vbmi2 -mno-gfni -mno-vpclmulqdq -mno-avx512vnni -mno-avx512bitalg -mno-avx512bf16 -mno-avx512vp2intersect -mno-3dnow -madx -mabm -mno-cldemote -mclflushopt -mno-clwb -mno-clzero -mcx16 -mno-enqcmd -mf16c -mfsgsbase -mfxsr -mhle -msahf -mno-lwp -mlzcnt -mmovbe -mno-movdir64b -mno-movdiri -mno-mwaitx -mno-pconfig -mno-pku -mprfchw -mno-ptwrite -mno-rdpid -mrdrnd -mrdseed -mrtm -mno-serialize -mno-sgx -mno-sha -mno-shstk -mno-tbm -mno-tsxldtrk -mno-vaes -mno-waitpkg -mno-wbnoinvd -mxsave -mxsavec -mxsaveopt -mxsaves -mno-amx-tile -mno-amx-int8 -mno-amx-bf16 -mno-uintr -mno-hreset -mno-kl -mno-widekl -mno-avxvnni -mno-avx512fp16 -mno-avxifma -mno-avxvnniint8 -mno-avxneconvert -mno-cmpccxadd -mno-amx-fp16 -mno-prefetchi -mno-raoint -mno-amx-complex -mno-avxvnniint16 -mno-sm3 -mno-sha512 -mno-sm4 -mno-apxf -mno-usermsr --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=8192 -mtune=skylake -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"c:\Users\Tsegaye\anaconda3\Lib\site-packages\numpy\core\include" -I"c:\Users\Tsegaye\anaconda3\include" -I"c:\Users\Tsegaye\anaconda3\Lib\site-packages\pytensor\link\c\c_code" -L"c:\Users\Tsegaye\anaconda3\libs" -L"c:\Users\Tsegaye\anaconda3" -o "C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\lazylinker_ext.pyd" "C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\mod.cpp" "c:\Users\Tsegaye\anaconda3\python312.dll"
In file included from c:\Users\Tsegaye\anaconda3\include/Python.h:12,
                 from c:\Users\Tsegaye\anaconda3\Lib\site-packages\pytensor\link\c\c_code/pytensor_mod_helper.h:4,
                 from C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\mod.cpp:1:
c:\Users\Tsegaye\anaconda3\include/pyconfig.h:240:9: warning: "MS_WIN64" redefined
  240 | #define MS_WIN64
      |         ^~~~~~~~
<command-line>: note: this is the location of the previous definition
cc1plus.exe: note: unrecognized command-line option '-Wno-c++11-narrowing' may have been intended to silence earlier diagnostics
collect2.exe: error: ld returned 116 exit status

2025-02-24 09:44:43,924 - logger - INFO - CUSUM plot created successfully.
2025-02-24 09:47:59,773 - logger - ERROR - Error in Bayesian change point analysis: Compilation failed (return status=1):
"C:\msys64\ucrt64\bin\g++.EXE" -shared -g -Wno-c++11-narrowing -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -march=skylake -mmmx -mpopcnt -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -mavx2 -mno-sse4a -mno-fma4 -mno-xop -mfma -mno-avx512f -mbmi -mbmi2 -maes -mpclmul -mno-avx512vl -mno-avx512bw -mno-avx512dq -mno-avx512cd -mno-avx512vbmi -mno-avx512ifma -mno-avx512vpopcntdq -mno-avx512vbmi2 -mno-gfni -mno-vpclmulqdq -mno-avx512vnni -mno-avx512bitalg -mno-avx512bf16 -mno-avx512vp2intersect -mno-3dnow -madx -mabm -mno-cldemote -mclflushopt -mno-clwb -mno-clzero -mcx16 -mno-enqcmd -mf16c -mfsgsbase -mfxsr -mhle -msahf -mno-lwp -mlzcnt -mmovbe -mno-movdir64b -mno-movdiri -mno-mwaitx -mno-pconfig -mno-pku -mprfchw -mno-ptwrite -mno-rdpid -mrdrnd -mrdseed -mrtm -mno-serialize -mno-sgx -mno-sha -mno-shstk -mno-tbm -mno-tsxldtrk -mno-vaes -mno-waitpkg -mno-wbnoinvd -mxsave -mxsavec -mxsaveopt -mxsaves -mno-amx-tile -mno-amx-int8 -mno-amx-bf16 -mno-uintr -mno-hreset -mno-kl -mno-widekl -mno-avxvnni -mno-avx512fp16 -mno-avxifma -mno-avxvnniint8 -mno-avxneconvert -mno-cmpccxadd -mno-amx-fp16 -mno-prefetchi -mno-raoint -mno-amx-complex -mno-avxvnniint16 -mno-sm3 -mno-sha512 -mno-sm4 -mno-apxf -mno-usermsr --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=8192 -mtune=skylake -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"c:\Users\Tsegaye\anaconda3\Lib\site-packages\numpy\core\include" -I"c:\Users\Tsegaye\anaconda3\include" -I"c:\Users\Tsegaye\anaconda3\Lib\site-packages\pytensor\link\c\c_code" -L"c:\Users\Tsegaye\anaconda3\libs" -L"c:\Users\Tsegaye\anaconda3" -o "C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\lazylinker_ext.pyd" "C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\mod.cpp" "c:\Users\Tsegaye\anaconda3\python312.dll"
In file included from c:\Users\Tsegaye\anaconda3\include/Python.h:12,
                 from c:\Users\Tsegaye\anaconda3\Lib\site-packages\pytensor\link\c\c_code/pytensor_mod_helper.h:4,
                 from C:\Users\Tsegaye\AppData\Local\PyTensor\compiledir_Windows-11-10.0.22621-SP0-Intel64_Family_6_Model_142_Stepping_10_GenuineIntel-3.12.3-64\lazylinker_ext\mod.cpp:1:
c:\Users\Tsegaye\anaconda3\include/pyconfig.h:240:9: warning: "MS_WIN64" redefined
  240 | #define MS_WIN64
      |         ^~~~~~~~
<command-line>: note: this is the location of the previous definition
cc1plus.exe: note: unrecognized command-line option '-Wno-c++11-narrowing' may have been intended to silence earlier diagnostics
collect2.exe: error: ld returned 116 exit status

2025-02-24 09:57:29,733 - logger - INFO - CUSUM plot created successfully.
